#开发配置

#tomcat配置
server:
  port: 8088
  servlet:
    #context-path: /manages

#spring配置
spring:
  #mvc配置
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .html
      prefix: /
  #热部署
  devtools:
    restart:
      enabled: true
      additional-exclude: WEB-INF/**
  #resources配置
  resources:
    static-locations: classpath:/static/
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.185.221:3306/gamerdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: gamer
    password: gamer123456
    tomcat:
      initial-size:
  #    druid:
#      #url: jdbc:mysql://47.106.185.221:3306/gamerdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#      #url: jdbc:mysql://47.106.185.221:3306/gamerdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#      url: jdbc:mysql://server.201.hydzfp.com:60003/invoiceCheck?useUnicode=true&amp;characterEncoding=UTF-8
#      username: gamer
#      password: gamer123456
#
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#
#      filters: stat,wall,log4j
#      max-pool-prepared-statement-per-connection-size: 20
#      use-global-data-source-stat: true
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    url:

  #模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

#mybatis配置
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*/*Mapper.xml
  type-aliases-package: com.ral.manages.entity

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
