#开发配置

#web
server:
  port: 8888
#resources datasource
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .html
      prefix: /
  resources:
    static-locations: classpath:/static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://47.106.185.221:3306/gamerdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: gamer
      password: gamer123456
      filters: stat,wall

#mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*/*Mapper.xml
  type-aliases-package: com.ral.manages.entity

